- name: installing the service manually
  hosts: 162.248.100.21
  tasks:
  - name: copying service file to target
    ansible.builtin.copy:
      src: service_name/fredboat.service
      dest: /etc/systemd/system/
